### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by YamadaHideki** [retailcoder/VBA-StringBuilder#4]
Hi. This code compiling error: Variable not defined. Can u help?
Private Property Get IsDefaultInstance() As Boolean
        **IsDefaultInstance = Me Is StringBuilder**
End Property

**Comment by retailcoder** [comment]
If the class module is named **StringBuilder**, the only reason for `Me Is StringBuilder` to fail compiling would be if the `VB_PredeclaredId` attribute of the `StringBuilder` module was not set to `True`, or somehow reverted back to `False`.
Did you copy/paste the code and ignored the attributes? These source files should be _imported_ into a VBA project in order to keep the attributes.

**Comment by YamadaHideki** [comment]
When I import a class, it is added to the module catalog. That's why I copy the code and create a new class. Everything works except this method. I also don't really understand what this method is trying to do.

**Comment by retailcoder** [comment]
The VB_PredeclaredId attribute must be set to True in order for the `StringBuilder` global identifier to exist. The IsDefaultInstance function is trying to determine whether a member call is being made against the default instance of the class.

Only classes with VB_PredeclaredId=True have a default instance, but this attribute cannot be modified in the VBE, that's why the source file must be imported and not pasted in.

**Comment by YamadaHideki** [comment]
I understand what u are talking about but i can't import the class it stands up as a module. Check it on the GIF please. Maybe you have faced something like this?
https://gifyu.com/image/SZxqj

**Comment by cristianbuse** [comment]
@YamadaHideki ,

You need to download the [zip](https://github.com/retailcoder/VBA-StringBuilder/archive/refs/heads/master.zip), extract the class and import from there.

**Comment by YamadaHideki** [comment]
Thank you all, i did it)
